/*
 * List of some useful object identifiers (OIDs)
 *
 * Copyright (C) 2003-2004 Andreas Steffen, Zuercher Hochschule Winterthur
 * Copyright (C) 2014 Tuomo Soini <tis@foobar.fi>
 *
 * This file has been generated by the script lib/libswan/oid.pl
 * Do not edit manually!
 */
#include "oid.h"

const struct oid oid_names[] = {
	/* octet, down, next, name */
	{ 0x02,                       true,    7, "ITU-T Administration"    },  /*   0 */
	{   0x82,                     true,    0, ""                        },  /*   1 */
	{     0x06,                   true,    0, "Germany ITU-T member"    },  /*   2 */
	{       0x01,                 true,    0, "Deutsche Telekom AG"     },  /*   3 */
	{         0x0A,               true,    0, ""                        },  /*   4 */
	{           0x07,             true,    0, ""                        },  /*   5 */
	{             0x14,           false,   0, "ND"                      },  /*   6 */
	{ 0x09,                       true,   18, "data"                    },  /*   7 */
	{   0x92,                     true,    0, ""                        },  /*   8 */
	{     0x26,                   true,    0, ""                        },  /*   9 */
	{       0x89,                 true,    0, ""                        },  /*  10 */
	{         0x93,               true,    0, ""                        },  /*  11 */
	{           0xF2,             true,    0, ""                        },  /*  12 */
	{             0x2C,           true,    0, ""                        },  /*  13 */
	{               0x64,         true,    0, "pilot"                   },  /*  14 */
	{                 0x01,       true,    0, "pilotAttributeType"      },  /*  15 */
	{                   0x01,     false,  17, "UID"                     },  /*  16 */
	{                   0x19,     false,   0, "DC"                      },  /*  17 */
	{ 0x55,                       true,   51, "X.500"                   },  /*  18 */
	{   0x04,                     true,   36, "X.509"                   },  /*  19 */
	{     0x03,                   false,  21, "CN"                      },  /*  20 */
	{     0x04,                   false,  22, "S"                       },  /*  21 */
	{     0x05,                   false,  23, "SN"                      },  /*  22 */
	{     0x06,                   false,  24, "C"                       },  /*  23 */
	{     0x07,                   false,  25, "L"                       },  /*  24 */
	{     0x08,                   false,  26, "ST"                      },  /*  25 */
	{     0x0A,                   false,  27, "O"                       },  /*  26 */
	{     0x0B,                   false,  28, "OU"                      },  /*  27 */
	{     0x0C,                   false,  29, "T"                       },  /*  28 */
	{     0x0D,                   false,  30, "D"                       },  /*  29 */
	{     0x24,                   false,  31, "userCertificate"         },  /*  30 */
	{     0x29,                   false,  32, "N"                       },  /*  31 */
	{     0x2A,                   false,  33, "G"                       },  /*  32 */
	{     0x2B,                   false,  34, "I"                       },  /*  33 */
	{     0x2D,                   false,  35, "ID"                      },  /*  34 */
	{     0x48,                   false,   0, "role"                    },  /*  35 */
	{   0x1d,                     true,    0, "id-ce"                   },  /*  36 */
	{     0x09,                   false,  38, "subjectDirectoryAttrs"   },  /*  37 */
	{     0x0E,                   false,  39, "subjectKeyIdentifier"    },  /*  38 */
	{     0x0F,                   false,  40, "keyUsage"                },  /*  39 */
	{     0x10,                   false,  41, "privateKeyUsagePeriod"   },  /*  40 */
	{     0x11,                   false,  42, "subjectAltName"          },  /*  41 */
	{     0x12,                   false,  43, "issuerAltName"           },  /*  42 */
	{     0x13,                   false,  44, "basicConstraints"        },  /*  43 */
	{     0x15,                   false,  45, "reasonCode"              },  /*  44 */
	{     0x1F,                   false,  46, "crlDistributionPoints"   },  /*  45 */
	{     0x20,                   false,  47, "certificatePolicies"     },  /*  46 */
	{     0x23,                   false,  48, "authorityKeyIdentifier"  },  /*  47 */
	{     0x25,                   false,  49, "extendedKeyUsage"        },  /*  48 */
	{     0x37,                   false,  50, "targetInformation"       },  /*  49 */
	{     0x38,                   false,   0, "noRevAvail"              },  /*  50 */
	{ 0x2A,                       true,   80, ""                        },  /*  51 */
	{   0x86,                     true,    0, ""                        },  /*  52 */
	{     0x48,                   true,    0, ""                        },  /*  53 */
	{       0x86,                 true,    0, ""                        },  /*  54 */
	{         0xF7,               true,    0, ""                        },  /*  55 */
	{           0x0D,             true,    0, "RSADSI"                  },  /*  56 */
	{             0x01,           true,   77, "PKCS"                    },  /*  57 */
	{               0x01,         true,   67, "PKCS-1"                  },  /*  58 */
	{                 0x01,       false,  60, "rsaEncryption"           },  /*  59 */
	{                 0x02,       false,  61, "md2WithRSAEncryption"    },  /*  60 */
	{                 0x04,       false,  62, "md5WithRSAEncryption"    },  /*  61 */
	{                 0x05,       false,  63, "sha-1WithRSAEncryption"  },  /*  62 */
	{                 0x0B,       false,  64, "sha256WithRSAEncryption" },  /*  63 */
	{                 0x0C,       false,  65, "sha384WithRSAEncryption" },  /*  64 */
	{                 0x0D,       false,  66, "sha512WithRSAEncryption" },  /*  65 */
	{                 0x0E,       false,   0, "sha224WithRSAEncryption" },  /*  66 */
	{               0x07,         true,   74, "PKCS-7"                  },  /*  67 */
	{                 0x01,       false,  69, "data"                    },  /*  68 */
	{                 0x02,       false,  70, "signedData"              },  /*  69 */
	{                 0x03,       false,  71, "envelopedData"           },  /*  70 */
	{                 0x04,       false,  72, "signedAndEnvelopedData"  },  /*  71 */
	{                 0x05,       false,  73, "digestedData"            },  /*  72 */
	{                 0x06,       false,   0, "encryptedData"           },  /*  73 */
	{               0x09,         true,    0, "PKCS-9"                  },  /*  74 */
	{                 0x01,       false,  76, "E"                       },  /*  75 */
	{                 0x02,       false,   0, "unstructuredName"        },  /*  76 */
	{             0x02,           true,    0, "digestAlgorithm"         },  /*  77 */
	{               0x02,         false,  79, "md2"                     },  /*  78 */
	{               0x05,         false,   0, "md5"                     },  /*  79 */
	{ 0x2B,                       true,  133, ""                        },  /*  80 */
	{   0x06,                     true,  121, "dod"                     },  /*  81 */
	{     0x01,                   true,    0, "internet"                },  /*  82 */
	{       0x04,                 true,   92, "private"                 },  /*  83 */
	{         0x01,               true,    0, "enterprise"              },  /*  84 */
	{           0x89,             true,    0, ""                        },  /*  85 */
	{             0x31,           true,    0, ""                        },  /*  86 */
	{               0x01,         true,    0, ""                        },  /*  87 */
	{                 0x01,       true,    0, ""                        },  /*  88 */
	{                   0x02,     true,    0, ""                        },  /*  89 */
	{                     0x02,   true,    0, ""                        },  /*  90 */
	{                       0x4B, false,   0, "TCGID"                   },  /*  91 */
	{       0x05,                 true,    0, "security"                },  /*  92 */
	{         0x05,               true,    0, "mechanisms"              },  /*  93 */
	{           0x07,             true,    0, "id-pkix"                 },  /*  94 */
	{             0x01,           true,   97, "id-pe"                   },  /*  95 */
	{               0x01,         false,   0, "authorityInfoAccess"     },  /*  96 */
	{             0x03,           true,  107, "id-kp"                   },  /*  97 */
	{               0x01,         false,  99, "serverAuth"              },  /*  98 */
	{               0x02,         false, 100, "clientAuth"              },  /*  99 */
	{               0x03,         false, 101, "codeSigning"             },  /* 100 */
	{               0x04,         false, 102, "emailProtection"         },  /* 101 */
	{               0x05,         false, 103, "ipsecEndSystem"          },  /* 102 */
	{               0x06,         false, 104, "ipsecTunnel"             },  /* 103 */
	{               0x07,         false, 105, "ipsecUser"               },  /* 104 */
	{               0x08,         false, 106, "timeStamping"            },  /* 105 */
	{               0x09,         false,   0, "ocspSigning"             },  /* 106 */
	{             0x0A,           true,  112, "id-aca"                  },  /* 107 */
	{               0x01,         false, 109, "authenticationInfo"      },  /* 108 */
	{               0x02,         false, 110, "accessIdentity"          },  /* 109 */
	{               0x03,         false, 111, "chargingIdentity"        },  /* 110 */
	{               0x04,         false,   0, "group"                   },  /* 111 */
	{             0x30,           true,    0, "id-ad"                   },  /* 112 */
	{               0x01,         true,    0, "ocsp"                    },  /* 113 */
	{                 0x01,       false, 115, "basic"                   },  /* 114 */
	{                 0x02,       false, 116, "nonce"                   },  /* 115 */
	{                 0x03,       false, 117, "crl"                     },  /* 116 */
	{                 0x04,       false, 118, "response"                },  /* 117 */
	{                 0x05,       false, 119, "noCheck"                 },  /* 118 */
	{                 0x06,       false, 120, "archiveCutoff"           },  /* 119 */
	{                 0x07,       false,   0, "serviceLocator"          },  /* 120 */
	{   0x0E,                     true,  126, "oiw"                     },  /* 121 */
	{     0x03,                   true,    0, "secsig"                  },  /* 122 */
	{       0x02,                 true,    0, "algorithms"              },  /* 123 */
	{         0x1A,               false, 125, "sha-1"                   },  /* 124 */
	{         0x1D,               false,   0, "sha-1WithRSASignature"   },  /* 125 */
	{   0x24,                     true,    0, "TeleTrusT"               },  /* 126 */
	{     0x03,                   true,    0, "algorithm"               },  /* 127 */
	{       0x03,                 true,    0, "signatureAlgorithm"      },  /* 128 */
	{         0x01,               true,    0, "rsaSignature"            },  /* 129 */
	{           0x02,             false, 131, "rsaSigWithripemd160"     },  /* 130 */
	{           0x03,             false, 132, "rsaSigWithripemd128"     },  /* 131 */
	{           0x04,             false,   0, "rsaSigWithripemd256"     },  /* 132 */
	{ 0x60,                       true,    0, ""                        },  /* 133 */
	{   0x86,                     true,    0, ""                        },  /* 134 */
	{     0x48,                   true,    0, ""                        },  /* 135 */
	{       0x01,                 true,    0, "organization"            },  /* 136 */
	{         0x65,               true,  144, "gov"                     },  /* 137 */
	{           0x03,             true,    0, "csor"                    },  /* 138 */
	{             0x04,           true,    0, "nistalgorithm"           },  /* 139 */
	{               0x02,         true,    0, "hashalgs"                },  /* 140 */
	{                 0x01,       false, 142, "id-SHA-256"              },  /* 141 */
	{                 0x02,       false, 143, "id-SHA-384"              },  /* 142 */
	{                 0x03,       false,   0, "id-SHA-512"              },  /* 143 */
	{         0x86,               true,    0, ""                        },  /* 144 */
	{           0xf8,             true,    0, ""                        },  /* 145 */
	{             0x42,           true,    0, ""                        },  /* 146 */
	{               0x01,         true,    0, ""                        },  /* 147 */
	{                 0x01,       false, 149, "nsCertType"              },  /* 148 */
	{                 0x03,       false, 150, "nsRevocationUrl"         },  /* 149 */
	{                 0x0d,       false,   0, "nsComment"               }   /* 150 */
};
