name: Bug Report
description: File a bug report.
body:
  - type: textarea
    attributes:
      label: Please Tell Us About Your System
      description: |
        - what is the local machine's Operating System?
          Please include the output from `uname -a`
        - which Liberswan version is the local machine running?
          Please include the output from `ipsec whack --version`.
          You're more likely to get someones attention when the problem has been reproduced in the current release
          (remember that this is a volunteer project, if you have an urgent problem that cannot wait, consider one
          of the [commercial support options](https://libreswan.org/wiki/Support)
        - is the peer different?
          If so, please include its details.
        - are you using IKEv1 or IKEv2?
          Since IKEv1 is [deprecated](https://www.rfc-editor.org/rfc/rfc9395) you're more likely to get attention when an IKEv1 problem is also demonstrated using IKEv2.
          However, we're still interested in interop. issues and crashes.
        - are you using ESP or AH, TRANSPORT or TUNNEL mode, IPCOMP, IP-TFS?
          AH has been made obsolete by ESP and NULL authentication (the only exception is AH+TRANSPORT).
        - (on Linux) are you using VTI or IPsec Interfaces (XFRMI)?
          If you're using VTI then please try IPsec Interfaces.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Please Tell Us What Happened?
      description: |
        Also tell us, what you expected to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Relevant log output
      description: Please copy and paste the relevant log output
      placeholder: |
        - if necessary remove sensitive details
          but keep as much information as possible
        - there is no need to include debug output
          most problems are better understood with just the standard logs
        - this will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    attributes:
      label: Your configuration
      description: Please copy and past your configuration file.
      placeholder: |
        - if necessary remove sensitive details
          but keep as much information as possible
        - this will be automatically formatted into code, so no need for backticks
      render: shell
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
    validations:
      required: false
